### ISSUE TITLE
Fails to convert 90.7183 kg and 90.7184 kg to pounds

### ISSUE THREAD

**Issue by Thaid** [FHIR/Ucum-java#10]
Using version 1.0.1
Running the following unit test
```
public static final String FILE = "essence.xml";

@Before
public void setup() throws Exception {
    URL thing = ConversionUnitTest.class.getClassLoader().getResource(FILE);
    mMyService = new UcumEssenceService(thing.openStream());
}

@Test
public void KgToPoundTest() throws UcumException {
    for (float i = 90.5f; i < 100f; i += 0.0001f) {
        Decimal decimal = new Decimal(Float.toString(i));
        float expectPound = i * 2.20462f;
        Decimal actual = mMyService.convert(decimal, "kg", "[lb_av]");
        if (Math.abs(Float.parseFloat(actual.asDecimal()) - expectPound) > 0.001) {
            System.out.println(i + " actual:" + actual.asDecimal() + " expected:" + expectPound);
        }
    }
}
```
The output:
```
90.7183 actual:110.000 expected:199.99937
90.7184 actual:110.000 expected:199.99959
```

The essence file is defined as: (It did not allow me to upload as xml)
[essence.xml.txt](https://github.com/FHIR/Ucum-java/files/2249960/essence.xml.txt)

**Comment by grahamegrieve** [comment]
I don't thnk that this is actually an error. internally, the factor being used is 2.2046226218487758072297380134503, derived from the values in the UCUM file. You've rounded this at the 6th decimal place to 2.20462. Then you've provided a value with 6 significant figures, and got back a value from the library that has 6 significant figures. But your test is rounding before the calculations, not after, and so your comparison value is wrong in the 6th figure. The calculated value before rounding at the 6th place is 199.99961639566379831300954202558565965296109367977243532557657440, which rounds to 110.000. Your expected value of 199.99937 is because you rounded first, not last

**Comment by grahamegrieve** [comment]
that was for 90.7183. for 90.7184, it's a significant figures problem as well.

**Comment by Thaid** [comment]
I don't believe rounding is the issue the number before and number after did not round. Did you perhaps misread the output?
```
90.7182 | actual: 199.999 | expected: 199.99914760522842
90.7183 | actual: 110.000 | expected: 199.99936806721686
90.7184 | actual: 110.000 | expected: 199.99958852920534
90.7185 | actual: 200.000 | expected: 199.9998089911938
```
This doesn't seem like a rounding issue when two middle conversions (90.7183, 90.7184) are incorrect, while the outer numbers (90.7182, 90.7185) as as expected.
I modified my test to:
```
@Test
    public void KgToPoundTest() throws UcumException {
        for (double i = 90.7182; i < 90.7186; i += 0.0001) {
            Decimal decimal = new Decimal(Double.toString(i));
            double expectPound = i * 2.20462f;
            Decimal actual = mMyService.convert(decimal, "kg", "[lb_av]");
            System.out.println(i + " | actual: " + actual.asDecimal() + " | expected: " + expectPound);
        }
    }
}
```

**Comment by Thaid** [comment]
I don't understand how 90.7183 kg would convert to 110.000 lb similarly
90.7184 kg would convert to 110.000 lb.
Using the example shouldn't rounding 199.99961639566379831300954202558565965296109367977243532557657440 at 6th sigfig round to 200.000?

**Comment by grahamegrieve** [comment]
I guess you could all this not seeing the forest for the trees. I've re-opened the issue and I'll try to get to it ASAP

**Comment by grahamegrieve** [comment]
ok fixed this time.
