### ISSUE TITLE
XPP dependency causes issues with Java 9+

### ISSUE THREAD

**Issue by brynrhodes** [FHIR/Ucum-java#14]
The following dependency:

```
<dependency>
  <groupId>xpp3</groupId>
  <artifactId>xpp3</artifactId>
  <version>1.1.4c</version>
</dependency>
```

causes issues when trying to build in Java 9+ because it defines a javax.xml.namespace.QName, resulting in multiple definitions of that class. Looking at the site, it doesn't seem to have much activity recently. I've looked for updates to this library and the [site](http://www.xmlpull.org/) doesn't seem to have been updated in quite a while. Anyone know of updates to this library?

It appears only to be used in the DefinitionParser and UcumTester classes to read the Ucum definitions and the test definitions, so it should be straightforward to replace if it comes to that.

**Comment by brynrhodes** [comment]
In Java 9+, you have to compile with a strictness setting of permissive in order for this to compile, as it's technically an issue in the Java compiler, being tracked here: https://stackoverflow.com/questions/51094274/eclipse-cant-find-xml-related-classes-after-switching-build-path-to-jdk-10

**Comment by grahamegrieve** [comment]
XPP has been removed
