### ISSUE TITLE
1.0-SNAPSHOT

### ISSUE THREAD

**Issue by teryfly** [FHIR/Ucum-java#18]
I want build the FHIR spec with the 'R4Final' version, but I cann't download the ucum from maven.
Where can I get the ‘1.0-SNAPSHOT’ version?

**Comment by grahamegrieve** [comment]
very probably you can't but there's no functional changes of relevance to 1.0 full version. 

btw, I cannot conceive of a reason for anyone but me to build the R4Final version of the spec

**Comment by teryfly** [comment]
I tried the 1.0 version, but the UcumException just show as below:

`[javac] import org.fhir.ucum.UcumException;
    [javac]                     ^
    [javac] /home/tery/git/fhir/implementations/java/org.hl7.fhir.dstu2/src/org/hl7/fhir/dstu2/utils/FHIRPathEngine.java:1557: error: cannot find symbol
    [javac]       Decimal d1;
    [javac]       ^
    [javac]   symbol:   class Decimal
    [javac]   location: class FHIRPathEngine
    [javac] /home/tery/git/fhir/implementations/java/org.hl7.fhir.dstu2/src/org/hl7/fhir/dstu2/utils/FHIRPathEngine.java:1559: error: cannot find symbol
    [javac]         d1 = new Decimal(l.primitiveValue());
    [javac]                  ^
    [javac]   symbol:   class Decimal
    [javac]   location: class FHIRPathEngine
    [javac] /home/tery/git/fhir/implementations/java/org.hl7.fhir.dstu2/src/org/hl7/fhir/dstu2/utils/FHIRPathEngine.java:1560: error: cannot find symbol
    [javac]         Decimal d2 = new Decimal(r.primitiveValue());
`

**Comment by teryfly** [comment]
I'm trying to translate the whole R4 sepc to Chinese

**Comment by brynrhodes** [comment]
That is certainly a worth cause! Maven central expires snapshots, looks like that's what happened in this case. I've just pushed a 1.0-SNAPSHOT from that point in the history, should be exactly what was there. Can you give a try again?

**Comment by teryfly** [comment]
> I've just pushed a 1.0-SNAPSHOT from that point in the history, should be exactly what was there. Can you give a try again?

where did you push to? I cann't find it in maven

` module not found: org.fhir#ucum;1.0-SNAPSHOT
[ivy:resolve]   ==== maven: tried
[ivy:resolve]     https://repo1.maven.org/maven2/org/fhir/ucum/1.0-SNAPSHOT/ucum-1.0-SNAPSHOT.pom
[ivy:resolve]     -- artifact org.fhir#ucum;1.0-SNAPSHOT!ucum.jar:
[ivy:resolve]     https://repo1.maven.org/maven2/org/fhir/ucum/1.0-SNAPSHOT/ucum-1.0-SNAPSHOT.jar
[ivy:resolve]   ==== maven-snapshots: tried
[ivy:resolve]     https://oss.sonatype.org/content/repositories/snapshots/org/fhir/ucum/1.0-SNAPSHOT/ucum-1.0-SNAPSHOT.pom
[ivy:resolve]     -- artifact org.fhir#ucum;1.0-SNAPSHOT!ucum.jar:
[ivy:resolve]     https://oss.sonatype.org/content/repositories/snapshots/org/fhir/ucum/1.0-SNAPSHOT/ucum-1.0-SNAPSHOT.jar
[ivy:resolve]   ==== bintray: tried
[ivy:resolve]     http://dl.bintray.com/labra/maven/org/fhir/ucum/1.0-SNAPSHOT/ucum-1.0-SNAPSHOT.pom
[ivy:resolve]     -- artifact org.fhir#ucum;1.0-SNAPSHOT!ucum.jar:
[ivy:resolve]     http://dl.bintray.com/labra/maven/org/fhir/ucum/1.0-SNAPSHOT/ucum-1.0-SNAPSHOT.jar
[ivy:resolve]   ==== jitpack: tried
[ivy:resolve]     https://jitpack.io/org/fhir/ucum/1.0-SNAPSHOT/ucum-1.0-SNAPSHOT.pom
[ivy:resolve]     -- artifact org.fhir#ucum;1.0-SNAPSHOT!ucum.jar:
[ivy:resolve]     https://jitpack.io/org/fhir/ucum/1.0-SNAPSHOT/ucum-1.0-SNAPSHOT.jar`

**Comment by brynrhodes** [comment]
I don't know why it wasn't there, I can see the metadata files were updated and reference 1.0-SNAPSHOT, but the directory wasn't there. So I deployed again and verified it is available now in the 1.0-SNAPSHOT directory:
https://oss.sonatype.org/content/repositories/snapshots/org/fhir/ucum/1.0-SNAPSHOT
Try again?

**Comment by grahamegrieve** [comment]
closing this - the fix is not to depend on the snapshot
