### ISSUE TITLE
Temp convert throws NPE instead of UcumException

### ISSUE THREAD

**Issue by labkey-matthewb** [FHIR/Ucum-java#22]
Decimal cel = ucum.convert(new Decimal("100", 15), "[degF]", "Cel");

results in:

        java.lang.NullPointerException: Cannot invoke "org.fhir.ucum.Decimal.divide(org.fhir.ucum.Decimal)" because "canValue" is null
            at org.fhir.ucum.UcumEssenceService.convert(UcumEssenceService.java:279)

It seems that ucum-java does not yet support linear (but not proportional) conversions, but should fail gracefully.

**Comment by grahamegrieve** [comment]
Added a test case to ensure it's UcumException
