### ISSUE TITLE
Multiple prefixes are not handled correctly.

### ISSUE THREAD

**Issue by metodski** [FHIR/Ucum-java#25]
In a ucum code, the unit can include multiple prefixes e.g. "mcg" which stands for milli-centi-gram. Both Milli and Centi prefixes are defined in the ucum-essence.xml yet the library only looks one-level deep when parsing the string for prefixes.

The problem appears when calling UcumService.validate("mcg")
Debugged the library a little bit and the problem appears to be at
[ExpressionParser.parseSymbol](https://github.com/FHIR/Ucum-java/blob/649b76330eb4cfb35e6db56d3ea8c03672f542a8/src/main/java/org/fhir/ucum/ExpressionParser.java#L96)

where 
`if (sym.startsWith(prefix.getCode())) {
				unit = model.getUnit(sym.substring(prefix.getCode().length()));`

In the case of "mcg", it sees that it starts with "m" and proceeds to look for a unit named "cg", instead of further checking for more prefixes and looking for the actual unit, which is "g".

**Comment by grahamegrieve** [comment]
I'm pretty sure that multiple prefixes are not allowed. Consider this, from the formal syntax rules:

```<simple-unit> | ::= | <ATOM-SYMBOL>\| <PREFIX-SYMBOL><ATOM-SYMBOL[metric]>```
