### ISSUE TITLE
When running current UCUM definition file a new error in UCUMValidator occurs

### ISSUE THREAD

**Issue by ghost** [FHIR/Ucum-java#5]
The error is probably Lexer related:
[m/s2/Hz^(1/2)]: Error processing unit '[m/s2/Hz^(1/2)]': The unit '[m' is unknown' at position 0

The current UCUM definition file is:
revision="$Revision: 442 $" revision-date="$Date: 2017-11-21 19:04:52 -0500 (Tue, 21 Nov 2017)

**Comment by BertVerhees** [comment]
This error can be repaired by adding a few conditions to the function isValidSymbolChar in Lexer.java

Add:
` || (inBrackets && ch == '/') || (inBrackets && ch == '(') || (inBrackets && ch == ')')`
