### ISSUE TITLE
Dart/Flutter version of Library

### ISSUE THREAD

**Issue by Dokotela** [FHIR/Ucum-java#51]
Thanks so much for your package! I don't program in Java, but I was able to use your package and convert it almost directly into Dart (with help from ChatGPT). My package is free and open source, found here: https://github.com/fhir-fli/ucum. I wanted to publish it to pub.dev, to allow anyone to use my library in their applications, but I wanted to ask about Permissions and Copyright issues before I did so. I've included a call out and link in the readme to this repo, and I've included the BSD-3 License on all of the files that mirror your files. Is there anything else I need to do prior to publication?

**Comment by grahamegrieve** [comment]
I don't think so.
